### ISSUE TITLE
bedrock_server executable not in package

### ISSUE THREAD

**Issue by mrsparx** [fourdollars/bedrock-docker#1]
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/bedrock/bedrock_server": stat /opt/bedrock/bedrock_server: no such file or directory: unknown

When browsing from the container the bedrock server executable isnt included. Is there any easy fix for this?

**Comment by fourdollars** [comment]
I can reduplicate the problem. Let me check what is going on.

**Comment by fourdollars** [comment]
https://github.com/fourdollars/playit-bedrock/actions/runs/11098933335/job/30832383932#step:3:445 
Microsoft changed HTTP protocol for the file hosting and it introduced the error of CURL.
```
#10 14.39 curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by mrsparx** [comment]
Confirmed fixed. Thank you! :)
